-- Creacion de tablas

CREATE TABLE DEPARTAMENTOS (
	CODIGO INTEGER PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(60),
	TELEFONO VARCHAR(20),
	WEB VARCHAR(50),
	FECHA_CREACION DATE
);

CREATE TABLE PROFESORES (
	NRP INTEGER PRIMARY KEY,
	NOMBRE VARCHAR(40) NOT NULL,
	APELLIDO1 VARCHAR(20) NOT NULL,
	APELLIDO2 VARCHAR(20),
	DEPARTAMENTO INTEGER REFERENCES DEPARTAMENTOS (CODIGO),
	TELEFONO VARCHAR(20),
	EMAIL VARCHAR(40),
	DIRECCION VARCHAR(60),
	FECHA_NACIMIENTO DATE,
	ANTIGUEDAD DATE,
	DIRECTOR_TESIS INTEGER REFERENCES PROFESORES (NRP)
);

CREATE TABLE DIRECTORES (
	NRP INTEGER PRIMARY KEY REFERENCES PROFESORES (NRP),
	SEXENIO INTEGER
);


CREATE TABLE ALUMNOS (
	DNI INTEGER PRIMARY KEY CHECK (DNI BETWEEN 1000000 AND 100000000),	-- le pongo int porque va a ser clave, y los limites son una estimacion de la racionalidad del dni
	NOMBRE VARCHAR(40) NOT NULL,
	APELLIDO1 VARCHAR(20) NOT NULL,
	APELLIDO2 VARCHAR(20),
	SEXO CHAR NOT NULL CHECK (SEXO IN ('f', 'm')),	-- aunque hoy en dia habria que considerar otros... xD
	DIRECCION VARCHAR(60),
	TELEFONO VARCHAR(20),
	EMAIL VARCHAR(40),
	FECHA_NACIMIENTO DATE,
	FECHA_PRIM_MATRICULA DATE
);

CREATE TABLE ASIGNATURAS (
	CODIGO INTEGER PRIMARY KEY,
	NOMBRE VARCHAR(40) NOT NULL,
	DEPARTAMENTO INTEGER REFERENCES DEPARTAMENTOS (CODIGO),
	CREDITOS INTEGER DEFAULT 0,
	TEORICOS INTEGER DEFAULT 0,
	PRACTICOS INTEGER DEFAULT 0,
	CARACTER CHAR(2) NOT NULL CHECK (CARACTER IN ('tr', 'ob', 'op')),	-- trONCAL, obLIGATORIA, opTATIVA
	CURSO INTEGER,
	WEB VARCHAR(50)
);

CREATE TABLE IMPARTIR (
	PROFESOR INTEGER REFERENCES PROFESORES (NRP),
	ASIGNATURA INTEGER REFERENCES ASIGNATURAS (CODIGO),
	TURNO CHAR NOT NULL,
	CARGA_CREDITOS INTEGER NOT NULL,
	PRIMARY KEY (PROFESOR, ASIGNATURA, TURNO, CARGA_CREDITOS)
);

CREATE TABLE MATRICULAR (
	ALUMNO INTEGER REFERENCES ALUMNOS (DNI),
	ASIGNATURA INTEGER REFERENCES ASIGNATURAS (CODIGO),
	TURNO CHAR NOT NULL,
	CALIFICACION INTEGER CHECK (CALIFICACION BETWEEN 0 AND 10)
);





